### ISSUE TITLE
FlagFile Path

### ISSUE THREAD

**Issue by Yashiroo** [spacemonkeygo/flagfile#3]
Hello,
I'm trying to read the path that is passed as flagfile argument within my code and then write to it the new flags. I'm unable to figure this out, i cannot find any built-in function that allows me to read this path.
Does anyone have any clarification regarding this?

**Comment by Yashiroo** [comment]
I've kind of rushed when opening the issue. I have solved this with the following line
flag.Lookup("flagfile").Value
Sorry, issue closed.

**Comment by jtolds** [comment]
that will do it!
